import { slugify } from "./lib/slug";

const volumeDefinitions = [
  {
    id: "volume-1",
    title: "Volume I",
    subtitle: "Mainly Mechanics, Radiation, and Heat",
    chapterRange: "Ch. 1-52",
    accent: "#f59e0b",
    summary:
      "Foundations of motion, energy, waves, heat, and the first contact with relativity.",
    chapterTitles: [
      "Atoms in Motion",
      "Basic Physics",
      "The Relation of Physics to Other Sciences",
      "Conservation of Energy",
      "Time and Distance",
      "Probability",
      "The Theory of Gravitation",
      "Motion",
      "Newton's Laws of Dynamics",
      "Conservation of Momentum",
      "Vectors",
      "Characteristics of Force",
      "Work and Potential Energy",
      "Work and Energy (continued)",
      "Special Theory of Relativity",
      "Relativistic Energy and Momentum",
      "Space-Time",
      "Rotation in Two Dimensions",
      "Center of Mass; Moment of Inertia",
      "Rotation in Space",
      "Harmonic Motion",
      "Algebra",
      "Resonance",
      "Transients",
      "Linear Systems and Review",
      "Optics: The Principle of Least Time",
      "Geometrical Optics",
      "Electromagnetic Radiation",
      "Interference",
      "Diffraction",
      "Polarization",
      "Radiation Damping; Light Scattering",
      "Color Vision",
      "Relativity of Time",
      "Gravitation",
      "Mechanics in Curved Space-Time",
      "Quantum Behavior",
      "The Relation of Wave and Particle Viewpoints",
      "The Kinetic Theory of Gases",
      "Statistical Mechanics",
      "The Brownian Movement",
      "Applications of Kinetic Theory",
      "Diffusion",
      "The Laws of Thermodynamics",
      "Applications of Thermodynamics",
      "Ratchet and Pawl",
      "Sound",
      "Beats",
      "Modes",
      "Harmonics",
      "Waves",
      "Symmetry in Physical Laws",
    ],
  },
  {
    id: "volume-2",
    title: "Volume II",
    subtitle: "Mainly Electromagnetism and Matter",
    chapterRange: "Ch. 1-41",
    accent: "#10b981",
    summary:
      "Fields, forces, circuits, magnetism, and the material response of matter.",
    chapterTitles: [
      "Electrostatics",
      "Electric Fields in Matter",
      "Divergence of Electric Field",
      "The Electric Potential",
      "The Electric Field",
      "Gauss' Law",
      "Applications of Gauss' Law",
      "Capacitors",
      "Current and Resistance",
      "Kirchhoff's Laws",
      "Dielectrics",
      "Magnetostatics",
      "Magnetic Fields",
      "The Magnetic Force",
      "Vector Potential",
      "Magnetic Energy",
      "Induction",
      "The Maxwell Equations",
      "The Principle of Least Action",
      "Solutions of Maxwell's Equations in Free Space",
      "Solutions with Currents and Charges",
      "AC Circuits",
      "Cavity Resonators",
      "Waveguides",
      "Relativistic Effects in Electrical Phenomena",
      "Lorentz Transformation of Fields",
      "Field Energy and Field Momentum",
      "Electromagnetic Mass",
      "Motion of Charges in Electric and Magnetic Fields",
      "Crystals",
      "Polarization of Light",
      "Paramagnetism and Diamagnetism",
      "Ferromagnetism",
      "Magnetic Domains",
      "Magnetic Materials",
      "Dielectric Materials",
      "Elasticity",
      "Strength of Materials",
      "Liquids",
      "Flow of Fluids",
      "Curved Surfaces",
    ],
  },
  {
    id: "volume-3",
    title: "Volume III",
    subtitle: "Quantum Mechanics",
    chapterRange: "Ch. 1-21",
    accent: "#0ea5e9",
    summary:
      "Quantum behavior, amplitudes, spin, atoms, and condensed matter sketches.",
    chapterTitles: [
      "Quantum Behavior",
      "Wave-Particle Duality",
      "Probability Amplitudes",
      "Identical Particles",
      "Spin One",
      "Spin One-Half",
      "The Dependence of Amplitudes on Time",
      "The Hamiltonian Matrix",
      "The Ammonia Maser",
      "Other Two-State Systems",
      "More Two-State Systems",
      "The Hyperfine Splitting in Hydrogen",
      "Propagation in a Crystal Lattice",
      "Semiconductors",
      "The Independent Particle Approximation",
      "Angular Momentum",
      "Addition of Angular Momentum",
      "The Hydrogen Atom",
      "The Schrodinger Equation in a Central Field",
      "The Schrodinger Equation in a Classical Context",
      "Superconductivity (seminar-style epilogue)",
    ],
  },
];

export const volumes = volumeDefinitions.map((volume) => {
  const chapters = volume.chapterTitles.map((title, index) => ({
    index: index + 1,
    title,
    slug: slugify(title),
    label: `Ch. ${index + 1}`,
  }));

  return {
    id: volume.id,
    title: volume.title,
    subtitle: volume.subtitle,
    chapterRange: volume.chapterRange,
    accent: volume.accent,
    summary: volume.summary,
    chapters,
  };
});

export type Volume = (typeof volumes)[number];
export type Chapter = Volume["chapters"][number];
